{
 "title": "dbadelante",
 "time": { "from": "now-5m", "to": "now" },
 "panels": [
  {
   "title": "Estado de MySQL",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "bool" } },
   "targets": [
    { "expr": "mysql_up", "legendFormat": "Estado de MySQL" }
   ]
  },
  {
   "title": "Conexiones Activas MySQL",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "mysql_global_status_threads_connected",
     "legendFormat": "Conexiones Activas MySQL"
    }
   ]
  },
  {
   "title": "Queries por Segundo",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "rate(mysql_global_status_questions[5m])",
     "legendFormat": "Queris por Segundo"
    }
   ]
  }
 ]
}